name: asset_management_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^3.2.0
  dartz: ^0.10.1
  dotenv: ^4.2.0
  equatable: ^2.0.7
  json_serializable: ^6.11.1
  mysql1: ^0.20.0
  path: ^1.9.1
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
